<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.8.0 on darwin)" generated="20200505 23:04:27.802" rpa="false">
<suite id="s1" name="MyTest" source="/Source/RF-Schulung/02_RobotFiles/TestCases/13_RobotFreatures/MyTest.robot">
<test id="s1-t1" name="test">
<kw name="Open Browser">
<msg timestamp="20200505 23:04:27.890" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20200505 23:04:27.890" endtime="20200505 23:04:27.890"></status>
</kw>
<status status="FAIL" starttime="20200505 23:04:27.888" endtime="20200505 23:04:27.892" critical="yes">No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20200505 23:04:27.804" endtime="20200505 23:04:27.892"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="MyTest">MyTest</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200505 23:04:27.888" level="ERROR">Error in file '/Source/RF-Schulung/02_RobotFiles/TestCases/13_RobotFreatures/MyTest.robot': Initializing test library 'SeleniumLibrary' with no arguments failed: TypeError: replace_string() got an unexpected keyword argument 'custom_unescaper'
Traceback (most recent call last):
  File "/Users/rener/.vscode-oss/extensions/jacobphilip.danfoss-robotframework-debug-1.4.2/out/RobotFrameworkDebugHelpers/robotf/running/testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/SeleniumLibrary/__init__.py", line 441, in __init__
    BrowserManagementKeywords(self),
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 36, in __init__
    self._webdriver_creator = WebDriverCreator(self.log_dir)
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/SeleniumLibrary/base/librarycomponent.py", line 76, in log_dir
    logfile = BuiltIn().get_variable_value('${LOG FILE}')
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/robot/libraries/BuiltIn.py", line 1322, in get_variable_value
    return self._variables[self._get_var_name(name)]
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/robot/libraries/BuiltIn.py", line 1595, in _get_var_name
    match.resolve_base(self._variables)
  File "/Users/rener/.pyenv/versions/3.8.0/lib/python3.8/site-packages/robot/variables/search.py", line 88, in resolve_base
    self.base = variables.replace_string(</msg>
</errors>
</robot>
